# Generated by Django 2.0.1 on 2018-01-06 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
