# Generated by Django 2.0.1 on 2018-01-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseuser',
            name='name',
        ),
        migrations.AddField(
            model_name='courseuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
