# Generated by Django 2.0.1 on 2018-01-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursemodule_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.IntegerField(choices=[(1, 'Texto'), (2, 'Codigo'), (3, 'Video'), (4, 'Audio'), (5, 'links')], default=1),
        ),
    ]
