# Generated by Django 2.0.1 on 2018-01-24 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180124_0557'),
        ('courses', '0003_auto_20180116_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('user_student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserCourse')),
            ],
        ),
    ]
