# Generated by Django 2.0.1 on 2018-01-26 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursestudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='user_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
