# Generated by Django 2.0.1 on 2018-01-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Instructor'), (3, 'Estudiante.')], default=3),
        ),
    ]
