# Generated by Django 2.0.1 on 2018-01-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180116_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='username',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
