# Generated by Django 2.0.1 on 2018-01-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180124_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='first_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='last_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
